package modelo;
// Generated 5 dic. 2019 8:29:15 by Hibernate Tools 5.2.12.Final

/**
 * TViajes generated by hbm2java
 */
public class TViajes implements java.io.Serializable {

	private int codViaje;
	private String nombre;
	private Integer estacionorigen;
	private Integer estaciondestino;

	public TViajes() {
	}

	public TViajes(int codViaje, String nombre) {
		this.codViaje = codViaje;
		this.nombre = nombre;
	}

	public TViajes(int codViaje, String nombre, Integer estacionorigen, Integer estaciondestino) {
		this.codViaje = codViaje;
		this.nombre = nombre;
		this.estacionorigen = estacionorigen;
		this.estaciondestino = estaciondestino;
	}

	public int getCodViaje() {
		return this.codViaje;
	}

	public void setCodViaje(int codViaje) {
		this.codViaje = codViaje;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getEstacionorigen() {
		return this.estacionorigen;
	}

	public void setEstacionorigen(Integer estacionorigen) {
		this.estacionorigen = estacionorigen;
	}

	public Integer getEstaciondestino() {
		return this.estaciondestino;
	}

	public void setEstaciondestino(Integer estaciondestino) {
		this.estaciondestino = estaciondestino;
	}

}
